# Generated by Django 6.0.8 on 2026-08-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("product_updated", "Product updated"),
                    ("out_of_stock", "Out of stock"),
                    ("scrape_failed", "Scrape failed"),
                    ("new_products_found", "New products found"),
                    ("supplier_unavailable", "Supplier unavailable"),
                ],
                max_length=30,
            ),
        ),
    ]
