from django.core.management.base import BaseCommand
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from decimal import Decimal
from category.models import Category, SoftwareTypes
from store.models import SoftwareProduct


SOFTWARE_DATA = {
    'operating-system': {
        'type': 'Operating System',
        'products': [
            {
                'product_name': 'Microsoft Windows 11 Pro',
                'version': '23H2',
                'price': '199.00',
                'compare_price': '249.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'The latest Windows operating system designed for productivity, security, and performance. Windows 11 Pro includes advanced features like BitLocker encryption, Remote Desktop, Hyper-V virtualization, and Group Policy management.',
                'short_description': 'Professional-grade OS with advanced security and productivity features.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft,professional',
            },
            {
                'product_name': 'Microsoft Windows 11 Home',
                'version': '23H2',
                'price': '139.00',
                'compare_price': '159.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 11 Home delivers a trusted, secure, and familiar experience for everyday use. Features include the new Start menu, Snap Layouts, Microsoft Teams integration, and enhanced gaming capabilities.',
                'short_description': 'The everyday Windows experience with enhanced productivity and gaming.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft,home',
            },
            {
                'product_name': 'Microsoft Windows 10 Pro',
                'version': '22H2',
                'price': '149.00',
                'compare_price': '199.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 10 Pro builds on the Home version with powerful features for business and advanced users. Includes BitLocker, Remote Desktop, and Windows Sandbox for secure application testing.',
                'short_description': 'The familiar professional OS with enterprise-grade features.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft,professional',
            },
            {
                'product_name': 'Microsoft Windows 10 Home',
                'version': '22H2',
                'price': '99.00',
                'compare_price': '119.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 10 Home offers a familiar, fast, and secure experience with features like Cortana, Microsoft Edge browser, and Xbox integration for gaming.',
                'short_description': 'Fast, secure, and familiar Windows experience for home users.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft,home',
            },
            {
                'product_name': 'Microsoft Windows 8.1 Pro',
                'version': '8.1',
                'price': '99.00',
                'compare_price': '129.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 8.1 Pro combines the power of Windows 8 with enhanced navigation features including the return of the Start button, improved app management, and enterprise-level security.',
                'short_description': 'Professional OS with hybrid tablet-desktop interface.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft',
            },
            {
                'product_name': 'Microsoft Windows 7 Professional',
                'version': 'SP1',
                'price': '79.00',
                'compare_price': '99.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 7 Professional delivers a familiar and reliable desktop experience with business-oriented features like Domain Join, Remote Desktop, and Windows XP Mode for legacy application support.',
                'short_description': 'Reliable and familiar professional OS with legacy support.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft',
            },
            {
                'product_name': 'Ubuntu 24.04 LTS',
                'version': '24.04 LTS',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Canonical',
                'publisher': 'Canonical',
                'platforms': 'linux',
                'description': 'Ubuntu 24.04 LTS (Noble Numbat) is the latest long-term support release featuring a refined desktop experience, improved security, and 5 years of free security updates. Perfect for development, servers, and everyday computing.',
                'short_description': 'Free, open-source Linux OS with 5 years of LTS support.',
                'max_devices': 999,
                'tags': 'linux,ubuntu,os,open-source,free',
            },
            {
                'product_name': 'Ubuntu 22.04 LTS',
                'version': '22.04 LTS',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Canonical',
                'publisher': 'Canonical',
                'platforms': 'linux',
                'description': 'Ubuntu 22.04 LTS (Jammy Jellyfish) is a stable and reliable Linux distribution backed by Canonical. Features GNOME desktop, Snap package manager, and enterprise-grade security.',
                'short_description': 'Stable and reliable LTS release for production environments.',
                'max_devices': 999,
                'tags': 'linux,ubuntu,os,open-source,free',
            },
            {
                'product_name': 'Debian 12',
                'version': '12 (Bookworm)',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Debian Project',
                'publisher': 'Debian Project',
                'platforms': 'linux',
                'description': 'Debian 12 Bookworm is a free and open-source Linux distribution known for its stability and package management. The universal operating system suitable for desktops, servers, and embedded systems.',
                'short_description': 'The universal open-source OS known for rock-solid stability.',
                'max_devices': 999,
                'tags': 'linux,debian,os,open-source,free,stable',
            },
            {
                'product_name': 'Fedora Workstation 40',
                'version': '40',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Red Hat',
                'publisher': 'Fedora Project',
                'platforms': 'linux',
                'description': 'Fedora Workstation 40 is a cutting-edge Linux distribution featuring the latest GNOME desktop, modern development tools, and strong security features. Backed by Red Hat.',
                'short_description': 'Cutting-edge Linux OS with the latest features and tools.',
                'max_devices': 999,
                'tags': 'linux,fedora,os,open-source,free',
            },
            {
                'product_name': 'Arch Linux',
                'version': 'Rolling Release',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Arch Linux Team',
                'publisher': 'Arch Linux',
                'platforms': 'linux',
                'description': 'Arch Linux is a lightweight and flexible Linux distribution that follows a rolling-release model. Known for its simplicity, customizability, and the powerful Arch User Repository (AUR).',
                'short_description': 'Lightweight rolling-release Linux for power users.',
                'max_devices': 999,
                'tags': 'linux,arch,os,open-source,free,rolling',
            },
            {
                'product_name': 'Kali Linux',
                'version': '2024.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Offensive Security',
                'publisher': 'Offensive Security',
                'platforms': 'linux',
                'description': 'Kali Linux is the industry-standard penetration testing and security auditing distribution. Pre-loaded with hundreds of security tools for network analysis, vulnerability assessment, and digital forensics.',
                'short_description': 'Industry-standard penetration testing and security OS.',
                'max_devices': 999,
                'tags': 'linux,kali,security,os,open-source,free,penetration-testing',
            },
            {
                'product_name': 'Linux Mint 21',
                'version': '21.3 (Virginia)',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Linux Mint Team',
                'publisher': 'Linux Mint Project',
                'platforms': 'linux',
                'description': 'Linux Mint 21 is a beginner-friendly Linux distribution based on Ubuntu. Features the Cinnamon desktop environment with a classic and intuitive interface for users transitioning from Windows.',
                'short_description': 'Beginner-friendly Linux with a classic Windows-like interface.',
                'max_devices': 999,
                'tags': 'linux,mint,os,open-source,free,beginner',
            },
        ],
    },
    'office-suite': {
        'type': 'Office Suite',
        'products': [
            {
                'product_name': 'Microsoft Office 2024 Professional Plus',
                'version': '2024',
                'price': '439.00',
                'compare_price': '499.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'The complete office suite with Word, Excel, PowerPoint, Outlook, Access, Publisher, and OneNote. One-time purchase includes all core productivity tools for professional use.',
                'short_description': 'Full office suite with Word, Excel, PowerPoint, Outlook, Access, and Publisher.',
                'max_devices': 1,
                'tags': 'office,microsoft,productivity,word,excel',
            },
            {
                'product_name': 'Microsoft Office 2024 Home & Business',
                'version': '2024',
                'price': '249.00',
                'compare_price': '299.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos',
                'description': 'Essential office applications for home and small business. Includes Word, Excel, PowerPoint, Outlook, and OneNote with a one-time purchase for one computer.',
                'short_description': 'Essential office suite with Word, Excel, PowerPoint, and Outlook.',
                'max_devices': 1,
                'tags': 'office,microsoft,productivity,home,business',
            },
            {
                'product_name': 'Microsoft Office 2024 Home & Student',
                'version': '2024',
                'price': '149.00',
                'compare_price': '179.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos',
                'description': 'Perfect for students and families. Includes Word, Excel, PowerPoint, and OneNote for school projects, resumes, and household budgeting.',
                'short_description': 'Essential office apps for students and families.',
                'max_devices': 1,
                'tags': 'office,microsoft,student,productivity',
            },
            {
                'product_name': 'Microsoft 365 Personal',
                'version': '2024',
                'price': '6.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos,web,mobile',
                'description': 'Premium Office apps plus 1TB of OneDrive cloud storage, advanced security, and continuous updates. Works on PC, Mac, tablet, and phone.',
                'short_description': 'Premium Office suite with 1TB cloud storage for one person.',
                'max_devices': 5,
                'tags': 'office,microsoft,365,subscription,cloud',
            },
            {
                'product_name': 'Microsoft 365 Family',
                'version': '2024',
                'price': '9.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos,web,mobile',
                'description': 'Premium Office apps for up to 6 people with 1TB of OneDrive cloud storage each, advanced security, and continuous updates for the whole family.',
                'short_description': 'Premium Office suite with 1TB cloud storage for up to 6 people.',
                'max_devices': 5,
                'tags': 'office,microsoft,365,subscription,family',
            },
            {
                'product_name': 'LibreOffice',
                'version': '24.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'The Document Foundation',
                'publisher': 'The Document Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'LibreOffice is a powerful, free office suite compatible with Microsoft Office formats. Includes Writer (word processing), Calc (spreadsheets), Impress (presentations), Draw, Base (database), and Math.',
                'short_description': 'Powerful free office suite compatible with Microsoft formats.',
                'max_devices': 999,
                'tags': 'office,free,open-source,libreoffice,writer,calc',
            },
            {
                'product_name': 'Apache OpenOffice',
                'version': '4.1',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Apache Software Foundation',
                'publisher': 'Apache Software Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'Apache OpenOffice is a leading open-source office suite with word processing, spreadsheets, presentations, graphics, databases, and more. Fully compatible with Microsoft Office formats.',
                'short_description': 'Feature-rich open-source office suite for everyday productivity.',
                'max_devices': 999,
                'tags': 'office,free,open-source,apache,writer,calc',
            },
            {
                'product_name': 'OnlyOffice Docs',
                'version': '8.0',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Ascensio System SIA',
                'publisher': 'OnlyOffice',
                'platforms': 'windows,macos,linux,web',
                'description': 'OnlyOffice Docs is a free and open-source office suite that provides high compatibility with Microsoft Office formats. Features collaborative document editing, spreadsheets, and presentations.',
                'short_description': 'Collaborative office suite with excellent Microsoft format compatibility.',
                'max_devices': 999,
                'tags': 'office,free,open-source,collaborative,cloud',
            },
        ],
    },
    'design-creative': {
        'type': 'Design & Creative',
        'products': [
            {
                'product_name': 'Adobe Photoshop',
                'version': '2025',
                'price': '22.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'The industry standard for digital image editing and graphic design. Features AI-powered tools including Generative Fill, Neural Filters, advanced layer management, and professional-grade retouching capabilities.',
                'short_description': 'Industry-leading image editing and graphic design software.',
                'max_devices': 2,
                'tags': 'adobe,photoshop,design,photo-editing,graphic-design',
            },
            {
                'product_name': 'Adobe Illustrator',
                'version': '2025',
                'price': '22.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'The industry-standard vector graphics design software for creating logos, icons, illustrations, typography, and complex graphics for print, web, and video.',
                'short_description': 'Professional vector graphics design for logos and illustrations.',
                'max_devices': 2,
                'tags': 'adobe,illustrator,vector,design,graphics',
            },
            {
                'product_name': 'Adobe InDesign',
                'version': '2025',
                'price': '22.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'The premier page layout and design software for print and digital media. Ideal for creating magazines, brochures, eBooks, posters, and interactive PDFs.',
                'short_description': 'Professional page layout and publishing software.',
                'max_devices': 2,
                'tags': 'adobe,indesign,layout,publishing,print',
            },
            {
                'product_name': 'Adobe Creative Cloud All Apps',
                'version': '2025',
                'price': '54.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'Get access to 20+ creative desktop and mobile apps including Photoshop, Illustrator, InDesign, Premiere Pro, After Effects, and more. The complete creative toolkit.',
                'short_description': 'Complete collection of 20+ Adobe creative desktop and mobile apps.',
                'max_devices': 2,
                'tags': 'adobe,creative-cloud,design,complete-suite',
            },
            {
                'product_name': 'GIMP',
                'version': '2.10',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'The GIMP Team',
                'publisher': 'GNU Project',
                'platforms': 'windows,macos,linux',
                'description': 'GNU Image Manipulation Program is a powerful free and open-source image editor. Features advanced photo retouching, image composition, and image authoring tools comparable to professional software.',
                'short_description': 'Free and powerful open-source image editor.',
                'max_devices': 999,
                'tags': 'gimp,image-editor,free,open-source,photo',
            },
            {
                'product_name': 'Inkscape',
                'version': '1.3',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Inkscape Project',
                'publisher': 'Inkscape Project',
                'platforms': 'windows,macos,linux',
                'description': 'Inkscape is a professional vector graphics editor for creating illustrations, diagrams, logos, and complex artwork. Uses SVG as its native format with broad format compatibility.',
                'short_description': 'Professional free vector graphics editor for illustrations and logos.',
                'max_devices': 999,
                'tags': 'inkscape,vector,graphics,free,open-source,svg',
            },
            {
                'product_name': 'Blender',
                'version': '4.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Blender Foundation',
                'publisher': 'Blender Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'Blender is the free and open-source 3D creation suite supporting the entire 3D pipeline: modeling, rigging, animation, simulation, rendering, compositing, motion tracking, video editing, and game creation.',
                'short_description': 'Complete free 3D creation suite for modeling, animation, and rendering.',
                'max_devices': 999,
                'tags': 'blender,3d,modeling,animation,free,open-source',
            },
            {
                'product_name': 'Figma',
                'version': '2024',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Figma',
                'publisher': 'Figma Inc',
                'platforms': 'web,macos,windows',
                'description': 'Figma is a collaborative web-based UI/UX design tool. Teams can design, prototype, and gather feedback in real-time. Free starter plan with paid professional and organization tiers.',
                'short_description': 'Collaborative web-based UI/UX design and prototyping tool.',
                'max_devices': 999,
                'tags': 'figma,ui,ux,design,prototyping,collaboration',
            },
        ],
    },
    'video-editing': {
        'type': 'Video Editing',
        'products': [
            {
                'product_name': 'Adobe Premiere Pro',
                'version': '2025',
                'price': '22.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'The industry-leading video editing software for film, TV, and the web. Features AI-powered tools like Auto Reframe, Speech to Text, and advanced color grading.',
                'short_description': 'Professional video editing software for film, TV, and web.',
                'max_devices': 2,
                'tags': 'adobe,premiere,pro,video-editing,professional',
            },
            {
                'product_name': 'DaVinci Resolve',
                'version': '19',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Blackmagic Design',
                'publisher': 'Blackmagic Design',
                'platforms': 'windows,macos,linux',
                'description': 'DaVinci Resolve combines professional editing, color correction, visual effects, motion graphics, and audio post-production in one free application. The Studio version adds advanced features.',
                'short_description': 'Professional-grade video editing, color grading, and effects (free version).',
                'max_devices': 999,
                'tags': 'davinci,resolve,video-editing,color-grading,free',
            },
            {
                'product_name': 'DaVinci Resolve Studio',
                'version': '19',
                'price': '295.00',
                'compare_price': '399.00',
                'license_type': 'one_time',
                'developer': 'Blackmagic Design',
                'publisher': 'Blackmagic Design',
                'platforms': 'windows,macos,linux',
                'description': 'The paid version of DaVinci Resolve with advanced features including noise reduction, HDR grading, facial recognition, and collaborative workflow tools. One-time purchase includes lifetime updates.',
                'short_description': 'Professional color grading and video editing with advanced features.',
                'max_devices': 1,
                'tags': 'davinci,resolve,video-editing,professional,studio',
            },
            {
                'product_name': 'Shotcut',
                'version': '24.06',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Meltytech',
                'publisher': 'Meltytech',
                'platforms': 'windows,macos,linux',
                'description': 'Shotcut is a free, open-source, cross-platform video editor with support for a wide range of formats. Features include timeline editing, filters, transitions, and 4K resolution support.',
                'short_description': 'Free open-source video editor with broad format support.',
                'max_devices': 999,
                'tags': 'shotcut,video-editing,free,open-source,cross-platform',
            },
            {
                'product_name': 'OBS Studio',
                'version': '30.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'OBS Project',
                'publisher': 'OBS Project',
                'platforms': 'windows,macos,linux',
                'description': 'Open Broadcaster Software is a free and open-source software for video recording and live streaming. Used by millions for professional-quality streaming to Twitch, YouTube, Facebook, and more.',
                'short_description': 'Free open-source software for live streaming and recording.',
                'max_devices': 999,
                'tags': 'obs,streaming,recording,free,open-source,live',
            },
        ],
    },
    'antivirus-security': {
        'type': 'Antivirus & Security',
        'products': [
            {
                'product_name': 'Norton 360 Deluxe',
                'version': '2024',
                'price': '49.99',
                'compare_price': '79.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'NortonLifeLock',
                'publisher': 'Gen Digital',
                'platforms': 'windows,macos,android,ios',
                'description': 'Comprehensive security suite including antivirus, VPN, password manager, dark web monitoring, and 50GB cloud backup. Protects up to 5 devices.',
                'short_description': 'All-in-one security with VPN, password manager, and dark web monitoring.',
                'max_devices': 5,
                'tags': 'norton,antivirus,security,vpn,protection',
            },
            {
                'product_name': 'Bitdefender Total Security',
                'version': '2024',
                'price': '49.99',
                'compare_price': '74.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'Bitdefender',
                'publisher': 'Bitdefender',
                'platforms': 'windows,macos,android,ios',
                'description': 'Multi-layer protection against malware, ransomware, and phishing. Includes VPN, parental controls, webcam protection, and system optimization tools.',
                'short_description': 'Multi-layer protection with VPN, parental controls, and optimization.',
                'max_devices': 5,
                'tags': 'bitdefender,antivirus,security,vpn,parental-control',
            },
            {
                'product_name': 'Kaspersky Internet Security',
                'version': '2024',
                'price': '49.99',
                'compare_price': '69.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'Kaspersky',
                'publisher': 'Kaspersky Lab',
                'platforms': 'windows,macos,android,ios',
                'description': 'Advanced security against viruses, ransomware, and online threats. Features include safe banking, privacy protection, parental controls, and VPN.',
                'short_description': 'Advanced internet security with safe banking and privacy tools.',
                'max_devices': 5,
                'tags': 'kaspersky,antivirus,security,vpn,banking',
            },
            {
                'product_name': 'Malwarebytes Premium',
                'version': '2024',
                'price': '44.99',
                'compare_price': '59.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'Malwarebytes',
                'publisher': 'Malwarebytes',
                'platforms': 'windows,macos,android,ios',
                'description': 'Real-time protection against malware, ransomware, and malicious websites. Lightweight and fast, Malwarebytes complements traditional antivirus with advanced threat detection.',
                'short_description': 'Real-time anti-malware protection for advanced threat defense.',
                'max_devices': 5,
                'tags': 'malwarebytes,antivirus,security,anti-malware',
            },
            {
                'product_name': 'Avast Free Antivirus',
                'version': '2024',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Avast',
                'publisher': 'Gen Digital',
                'platforms': 'windows,macos,android,ios',
                'description': 'Free antivirus protection with intelligent threat detection, Wi-Fi security scanner, and password protection. Premium features available for upgrade.',
                'short_description': 'Free antivirus with smart threat detection and Wi-Fi security.',
                'max_devices': 1,
                'tags': 'avast,antivirus,security,free,protection',
            },
            {
                'product_name': 'ClamAV',
                'version': '1.3',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Cisco',
                'publisher': 'Cisco',
                'platforms': 'linux,windows,macos',
                'description': 'ClamAV is an open-source antivirus toolkit designed for detecting trojans, viruses, malware, and other malicious threats. Widely used on mail gateways and Linux servers.',
                'short_description': 'Open-source antivirus toolkit for threat detection.',
                'max_devices': 999,
                'tags': 'clamav,antivirus,security,open-source,free',
            },
        ],
    },
    'development-tools': {
        'type': 'Development Tools',
        'products': [
            {
                'product_name': 'Visual Studio Code',
                'version': '1.91',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos,linux',
                'description': 'Visual Studio Code is a lightweight but powerful source code editor with built-in support for JavaScript, TypeScript, Node.js, and a rich ecosystem of extensions for other languages.',
                'short_description': 'Lightweight, powerful source code editor with rich extension ecosystem.',
                'max_devices': 999,
                'tags': 'vscode,editor,microsoft,code,open-source,free',
            },
            {
                'product_name': 'Visual Studio 2022 Professional',
                'version': '2022',
                'price': '499.00',
                'compare_price': '599.00',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Full-featured IDE for professional developers. Supports C#, C++, Python, JavaScript, and more with debugging, testing, and team collaboration tools.',
                'short_description': 'Professional IDE for .NET, C++, and Python development.',
                'max_devices': 1,
                'tags': 'visual-studio,ide,microsoft,professional,development',
            },
            {
                'product_name': 'IntelliJ IDEA Ultimate',
                'version': '2024.2',
                'price': '249.00',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'JetBrains',
                'publisher': 'JetBrains',
                'platforms': 'windows,macos,linux',
                'description': 'The leading Java and Kotlin IDE with intelligent coding assistance, built-in developer tools, and support for a wide range of frameworks including Spring, Jakarta EE, and Android.',
                'short_description': 'Leading Java/Kotlin IDE with intelligent coding assistance.',
                'max_devices': 1,
                'tags': 'intellij,jetbrains,java,kotlin,ide',
            },
            {
                'product_name': 'PyCharm Professional',
                'version': '2024.2',
                'price': '249.00',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'JetBrains',
                'publisher': 'JetBrains',
                'platforms': 'windows,macos,linux',
                'description': 'The Python IDE for professional developers with intelligent code completion, debugging, testing, profiling, and support for web frameworks like Django, Flask, and FastAPI.',
                'short_description': 'Professional Python IDE with Django and scientific tool support.',
                'max_devices': 1,
                'tags': 'pycharm,jetbrains,python,ide,django',
            },
            {
                'product_name': 'Sublime Text',
                'version': '4',
                'price': '99.00',
                'compare_price': '99.00',
                'license_type': 'one_time',
                'developer': 'Sublime HQ',
                'publisher': 'Sublime HQ',
                'platforms': 'windows,macos,linux',
                'description': 'A sophisticated text editor for code, markup, and prose. Lightning-fast performance with Goto Anything, multiple selections, command palette, and a powerful Python API for plugins.',
                'short_description': 'Fast, sophisticated text editor for code and prose.',
                'max_devices': 1,
                'tags': 'sublime,editor,text,code,fast',
            },
            {
                'product_name': 'Git',
                'version': '2.45',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Git SCM',
                'publisher': 'Git Project',
                'platforms': 'windows,macos,linux',
                'description': 'Git is a free and open-source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.',
                'short_description': 'Industry-standard distributed version control system.',
                'max_devices': 999,
                'tags': 'git,version-control,open-source,free,vcs',
            },
            {
                'product_name': 'Docker Desktop',
                'version': '4.32',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Docker Inc',
                'publisher': 'Docker Inc',
                'platforms': 'windows,macos,linux',
                'description': 'Docker Desktop is an application for building, sharing, and running containerized applications. Includes Docker Engine, Kubernetes, Docker Compose, and a user-friendly interface.',
                'short_description': 'Containerization platform for building and sharing applications.',
                'max_devices': 999,
                'tags': 'docker,containers,devops,free,containerization',
            },
            {
                'product_name': 'Node.js',
                'version': '22.4',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'OpenJS Foundation',
                'publisher': 'OpenJS Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'Node.js is a JavaScript runtime built on Chrome V8 engine for building fast, scalable network applications. Perfect for server-side applications, APIs, and real-time services.',
                'short_description': 'JavaScript runtime for building scalable network applications.',
                'max_devices': 999,
                'tags': 'nodejs,javascript,runtime,server,open-source,free',
            },
            {
                'product_name': 'Python',
                'version': '3.12',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Python Software Foundation',
                'publisher': 'Python Software Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'Python is a versatile, high-level programming language known for its readability and broad ecosystem. Used for web development, data science, AI, automation, and scientific computing.',
                'short_description': 'Versatile high-level programming language for all domains.',
                'max_devices': 999,
                'tags': 'python,programming,language,open-source,free',
            },
        ],
    },
    'database-software': {
        'type': 'Database Software',
        'products': [
            {
                'product_name': 'MySQL',
                'version': '8.0',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Oracle',
                'publisher': 'Oracle Corporation',
                'platforms': 'windows,macos,linux',
                'description': 'MySQL is the worlds most popular open-source relational database management system. Known for reliability, performance, and ease of use. Ideal for web applications and e-commerce.',
                'short_description': 'Worlds most popular open-source relational database.',
                'max_devices': 999,
                'tags': 'mysql,database,open-source,sql,relational,free',
            },
            {
                'product_name': 'PostgreSQL',
                'version': '16',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'PostgreSQL Global Development Group',
                'publisher': 'PostgreSQL Project',
                'platforms': 'windows,macos,linux',
                'description': 'PostgreSQL is a powerful, open-source object-relational database system with over 30 years of active development. Known for reliability, feature robustness, and SQL compliance.',
                'short_description': 'Advanced open-source relational database with excellent reliability.',
                'max_devices': 999,
                'tags': 'postgresql,database,open-source,sql,free,advanced',
            },
            {
                'product_name': 'MongoDB',
                'version': '7.0',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'MongoDB Inc',
                'publisher': 'MongoDB Inc',
                'platforms': 'windows,macos,linux',
                'description': 'MongoDB is a source-available NoSQL document database designed for ease of development and scalability. Stores data in flexible JSON-like documents with powerful query capabilities.',
                'short_description': 'Leading NoSQL document database for modern applications.',
                'max_devices': 999,
                'tags': 'mongodb,database,nosql,document,free',
            },
            {
                'product_name': 'SQLite',
                'version': '3.46',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'D. Richard Hipp',
                'publisher': 'SQLite Consortium',
                'platforms': 'windows,macos,linux',
                'description': 'SQLite is a C-language library that implements a small, fast, self-contained, high-reliability SQL database engine. The most deployed database engine in the world.',
                'short_description': 'Self-contained, serverless SQL database engine.',
                'max_devices': 999,
                'tags': 'sqlite,database,embedded,sql,free,lightweight',
            },
            {
                'product_name': 'MariaDB',
                'version': '11.4',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'MariaDB Foundation',
                'publisher': 'MariaDB Corporation',
                'platforms': 'windows,macos,linux',
                'description': 'MariaDB is a community-developed fork of MySQL, designed as a drop-in replacement with enhanced features, better performance, and additional storage engines.',
                'short_description': 'Community-developed MySQL fork with enhanced performance.',
                'max_devices': 999,
                'tags': 'mariadb,database,sql,open-source,free,mysql',
            },
            {
                'product_name': 'Redis',
                'version': '7.4',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Redis Ltd',
                'publisher': 'Redis Ltd',
                'platforms': 'windows,macos,linux',
                'description': 'Redis is an in-memory data structure store used as a database, cache, and message broker. Supports strings, hashes, lists, sets, and more with built-in replication and persistence.',
                'short_description': 'In-memory data store for caching, real-time apps, and queues.',
                'max_devices': 999,
                'tags': 'redis,database,cache,in-memory,nosql,free',
            },
        ],
    },
    'remote-desktop-vpn': {
        'type': 'Remote Desktop & VPN',
        'products': [
            {
                'product_name': 'TeamViewer Remote',
                'version': '15',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'TeamViewer',
                'publisher': 'TeamViewer Germany GmbH',
                'platforms': 'windows,macos,linux,web,mobile',
                'description': 'TeamViewer is a leading remote desktop and support solution. Free for personal use with secure remote access, file transfer, and collaboration features.',
                'short_description': 'Secure remote desktop and support solution (free for personal use).',
                'max_devices': 999,
                'tags': 'teamviewer,remote-desktop,vpn,remote-access,free',
            },
            {
                'product_name': 'AnyDesk',
                'version': '8.0',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'AnyDesk',
                'publisher': 'AnyDesk Software GmbH',
                'platforms': 'windows,macos,linux,web,mobile',
                'description': 'AnyDesk offers lightning-fast remote desktop access with advanced security features. Free for personal use with low latency connections and file transfer capabilities.',
                'short_description': 'Fast remote desktop software with advanced security.',
                'max_devices': 999,
                'tags': 'anydesk,remote-desktop,remote-access,free',
            },
            {
                'product_name': 'OpenVPN',
                'version': '2.6',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'OpenVPN Inc',
                'publisher': 'OpenVPN Project',
                'platforms': 'windows,macos,linux,android,ios',
                'description': 'OpenVPN is a robust, highly configurable open-source VPN solution. Uses industry-standard SSL/TLS protocols for secure point-to-point tunneling and site-to-site connectivity.',
                'short_description': 'Secure open-source VPN for remote access and site-to-site connectivity.',
                'max_devices': 999,
                'tags': 'openvpn,vpn,security,open-source,free',
            },
            {
                'product_name': 'WireGuard',
                'version': '1.0',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'WireGuard',
                'publisher': 'WireGuard Project',
                'platforms': 'windows,macos,linux,android,ios',
                'description': 'WireGuard is a modern, fast, and secure VPN tunnel protocol designed for simplicity and performance. Features state-of-the-art cryptography and minimal attack surface.',
                'short_description': 'Modern, fast, and secure VPN protocol.',
                'max_devices': 999,
                'tags': 'wireguard,vpn,security,open-source,free,fast',
            },
            {
                'product_name': 'Cloudflare WARP',
                'version': '2024',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Cloudflare',
                'publisher': 'Cloudflare Inc',
                'platforms': 'windows,macos,linux,android,ios',
                'description': 'Cloudflare WARP replaces the connection between your device and the Internet with a modern, optimized, and secure protocol. Free version includes basic privacy protection.',
                'short_description': 'Secure, optimized internet connection with privacy protection.',
                'max_devices': 999,
                'tags': 'cloudflare,warp,vpn,privacy,security,free',
            },
        ],
    },
    'backup-recovery': {
        'type': 'Backup & Recovery',
        'products': [
            {
                'product_name': 'Acronis Cyber Protect Home Office',
                'version': '2024',
                'price': '49.99',
                'compare_price': '69.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'Acronis',
                'publisher': 'Acronis International GmbH',
                'platforms': 'windows,macos',
                'description': 'Complete backup and cybersecurity solution for home and business. Offers full-image backups, file-level backup, anti-malware, and vulnerability assessment.',
                'short_description': 'Complete backup and cybersecurity for home office users.',
                'max_devices': 3,
                'tags': 'acronis,backup,recovery,cybersecurity',
            },
            {
                'product_name': 'EaseUS Todo Backup Home',
                'version': '2024',
                'price': '29.95',
                'compare_price': '39.95',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'EaseUS',
                'publisher': 'EaseUS Software',
                'platforms': 'windows',
                'description': 'Reliable backup and recovery software with system backup, disk cloning, file backup, and cloud backup support. Easy-to-use interface for protecting important data.',
                'short_description': 'Easy backup and recovery with system and disk cloning support.',
                'max_devices': 1,
                'tags': 'easeus,backup,recovery,disk-cloning',
            },
            {
                'product_name': 'Veeam Agent for Linux',
                'version': '6.1',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Veeam',
                'publisher': 'Veeam Software',
                'platforms': 'linux',
                'description': 'Veeam Agent for Linux is a free backup solution for Linux servers and workstations. Offers volume-level backup, file-level restore, and integration with Veeam Backup & Replication.',
                'short_description': 'Free Linux backup with volume-level and file-level protection.',
                'max_devices': 999,
                'tags': 'veeam,backup,linux,free,open-source',
            },
            {
                'product_name': 'Duplicati',
                'version': '2.0',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Duplicati Team',
                'publisher': 'Duplicati Project',
                'platforms': 'windows,macos,linux',
                'description': 'Duplicati is a free, open-source backup client that securely stores encrypted backups on cloud storage services including Google Drive, Dropbox, OneDrive, and Amazon S3.',
                'short_description': 'Free encrypted cloud backup client supporting multiple providers.',
                'max_devices': 999,
                'tags': 'duplicati,backup,cloud,encrypted,free,open-source',
            },
        ],
    },
    'network-management': {
        'type': 'Network Management',
        'products': [
            {
                'product_name': 'Wireshark',
                'version': '4.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Wireshark Foundation',
                'publisher': 'Wireshark Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'Wireshark is the worlds most popular network protocol analyzer. Used for network troubleshooting, analysis, software development, and education. Captures and interactively browses traffic.',
                'short_description': 'Worlds most popular network protocol analyzer.',
                'max_devices': 999,
                'tags': 'wireshark,network,analyzer,protocol,sniffer,free',
            },
            {
                'product_name': 'PuTTY',
                'version': '0.81',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Simon Tatham',
                'publisher': 'PuTTY Project',
                'platforms': 'windows',
                'description': 'PuTTY is a free SSH and telnet client for Windows. Widely used for remote server administration with support for SSH, Telnet, Rlogin, and serial connections.',
                'short_description': 'Free SSH and telnet client for Windows remote administration.',
                'max_devices': 999,
                'tags': 'putty,ssh,telnet,remote,terminal,free',
            },
            {
                'product_name': 'Nmap',
                'version': '7.95',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Nmap Project',
                'publisher': 'Nmap Project',
                'platforms': 'windows,macos,linux',
                'description': 'Nmap (Network Mapper) is a free and open-source utility for network discovery and security auditing. Used for port scanning, OS detection, version detection, and network inventory.',
                'short_description': 'Free network discovery and security auditing tool.',
                'max_devices': 999,
                'tags': 'nmap,network,scanner,security,auditing,free',
            },
            {
                'product_name': 'OpenSSH',
                'version': '9.7',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'OpenBSD Project',
                'publisher': 'OpenBSD Project',
                'platforms': 'windows,macos,linux',
                'description': 'OpenSSH is the premier connectivity tool for remote login with the SSH protocol. Encrypts all traffic to eliminate eavesdropping, connection hijacking, and other attacks.',
                'short_description': 'Secure remote login and file transfer via SSH protocol.',
                'max_devices': 999,
                'tags': 'openssh,ssh,remote,security,free,open-source',
            },
        ],
    },
    'point-of-sale-pos': {
        'type': 'Point of Sale (POS)',
        'products': [
            {
                'product_name': 'Square POS',
                'version': '2024',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Block Inc',
                'publisher': 'Square',
                'platforms': 'web,mobile',
                'description': 'Square Point of Sale is a free, all-in-one POS system for managing sales, inventory, and customers. Accept payments, track sales, and manage employees with an intuitive interface.',
                'short_description': 'Free all-in-one POS system for sales and inventory management.',
                'max_devices': 999,
                'tags': 'square,pos,payment,inventory,sales',
            },
            {
                'product_name': 'Loyverse POS',
                'version': '2024',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Loyverse',
                'publisher': 'Loyverse',
                'platforms': 'web,mobile',
                'description': 'Loyverse is a free POS system designed for small retail shops and restaurants. Features include sales tracking, inventory management, customer loyalty programs, and employee management.',
                'short_description': 'Free POS for small retail and restaurants with loyalty programs.',
                'max_devices': 999,
                'tags': 'loyverse,pos,retail,restaurant,free',
            },
        ],
    },
    'accounting-finance': {
        'type': 'Accounting & Finance',
        'products': [
            {
                'product_name': 'GNUCash',
                'version': '5.5',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'GNUCash Development Team',
                'publisher': 'GNUCash Project',
                'platforms': 'windows,macos,linux',
                'description': 'GNUCash is a free, open-source accounting software for personal and small business finance. Features double-entry accounting, invoicing, bank reconciliation, and tax reporting.',
                'short_description': 'Free open-source accounting software for personal and small business.',
                'max_devices': 999,
                'tags': 'gnucash,accounting,finance,free,open-source',
            },
            {
                'product_name': 'Invoice Ninja',
                'version': '5.10',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Invoice Ninja',
                'publisher': 'Invoice Ninja',
                'platforms': 'web,mobile',
                'description': 'Invoice Ninja is a free, open-source invoicing and expense tracking platform. Features professional invoicing, time tracking, expense management, and payment processing integration.',
                'short_description': 'Free invoicing and expense tracking for freelancers and businesses.',
                'max_devices': 999,
                'tags': 'invoice-ninja,invoicing,accounting,free,open-source',
            },
        ],
    },
}


class Command(BaseCommand):
    help = 'Seeds the database with popular software products for the software section.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear existing software products before seeding.',
        )

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write(self.style.WARNING('Clearing existing software products...'))
            SoftwareProduct.objects.all().delete()

        try:
            software_category = Category.objects.get(slug='software')
        except Category.DoesNotExist:
            self.stdout.write(self.style.ERROR('Software category not found. Run seed_catalogue first.'))
            return

        for slug, group in SOFTWARE_DATA.items():
            try:
                software_type = SoftwareTypes.objects.get(slug=slug)
            except SoftwareTypes.DoesNotExist:
                self.stdout.write(self.style.WARNING(f'  Software type "{slug}" not found — skipping.'))
                continue

            section_created = 0
            for data in group['products']:
                base_slug = slugify(data['product_name'])
                _, created = SoftwareProduct.objects.get_or_create(
                    slug=base_slug,
                    defaults={
                        'product_name': data['product_name'],
                        'category': software_category,
                        'software_category': software_type,
                        'version': data['version'],
                        'price': data['price'],
                        'stock': 9999,
                        'is_available': True,
                        'is_digital': True,
                        'requires_shipping': False,
                        'track_inventory': False,
                        'description': data.get('description', ''),
                        'short_description': data.get('short_description', ''),
                        'tags': data.get('tags', ''),
                        'license_type': data['license_type'],
                        'platforms': data.get('platforms', 'web'),
                        'developer': data.get('developer', ''),
                        'publisher': data.get('publisher', ''),
                        'max_devices': data.get('max_devices', 1),
                        'subscription_duration': data.get('subscription_duration', None),
                        'compare_price': data.get('compare_price', None),
                        'condition': 'new',
                    }
                )
                if created:
                    section_created += 1

            self.stdout.write(
                f'  {group["type"]}: {section_created} created'
                if section_created
                else self.style.WARNING(f'  {group["type"]}: already exists')
            )

        total = SoftwareProduct.objects.count()
        self.stdout.write(self.style.SUCCESS(f'\n✅ {total} software products seeded successfully!\n'))
