from django.core.management.base import BaseCommand
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from decimal import Decimal
from category.models import Category, SoftwareTypes
from store.models import SoftwareProduct


SOFTWARE_DATA = {
    'operating-system': {
        'type': 'Operating System',
        'products': [
            {
                'product_name': 'Microsoft Windows 11 Pro',
                'version': '23H2',
                'price': '199.00',
                'compare_price': '249.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'The latest Windows operating system designed for productivity, security, and performance. Windows 11 Pro includes advanced features like BitLocker encryption, Remote Desktop, Hyper-V virtualization, and Group Policy management.',
                'short_description': 'Professional-grade OS with advanced security and productivity features.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft,professional',
            },
            {
                'product_name': 'Microsoft Windows 11 Home',
                'version': '23H2',
                'price': '139.00',
                'compare_price': '159.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 11 Home delivers a trusted, secure, and familiar experience for everyday use. Features include the new Start menu, Snap Layouts, Microsoft Teams integration, and enhanced gaming capabilities.',
                'short_description': 'The everyday Windows experience with enhanced productivity and gaming.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft,home',
            },
            {
                'product_name': 'Microsoft Windows 10 Pro',
                'version': '22H2',
                'price': '149.00',
                'compare_price': '199.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 10 Pro builds on the Home version with powerful features for business and advanced users. Includes BitLocker, Remote Desktop, and Windows Sandbox for secure application testing.',
                'short_description': 'The familiar professional OS with enterprise-grade features.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft,professional',
            },
            {
                'product_name': 'Microsoft Windows 10 Home',
                'version': '22H2',
                'price': '99.00',
                'compare_price': '119.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 10 Home offers a familiar, fast, and secure experience with features like Cortana, Microsoft Edge browser, and Xbox integration for gaming.',
                'short_description': 'Fast, secure, and familiar Windows experience for home users.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft,home',
            },
            {
                'product_name': 'Microsoft Windows 8.1 Pro',
                'version': '8.1',
                'price': '99.00',
                'compare_price': '129.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 8.1 Pro combines the power of Windows 8 with enhanced navigation features including the return of the Start button, improved app management, and enterprise-level security.',
                'short_description': 'Professional OS with hybrid tablet-desktop interface.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft',
            },
            {
                'product_name': 'Microsoft Windows 7 Professional',
                'version': 'SP1',
                'price': '79.00',
                'compare_price': '99.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'Windows 7 Professional delivers a familiar and reliable desktop experience with business-oriented features like Domain Join, Remote Desktop, and Windows XP Mode for legacy application support.',
                'short_description': 'Reliable and familiar professional OS with legacy support.',
                'max_devices': 1,
                'tags': 'windows,os,microsoft',
            },
            {
                'product_name': 'Ubuntu 24.04 LTS',
                'version': '24.04 LTS',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Canonical',
                'publisher': 'Canonical',
                'platforms': 'linux',
                'description': 'Ubuntu 24.04 LTS (Noble Numbat) is the latest long-term support release featuring a refined desktop experience, improved security, and 5 years of free security updates. Perfect for development, servers, and everyday computing.',
                'short_description': 'Free, open-source Linux OS with 5 years of LTS support.',
                'max_devices': 999,
                'tags': 'linux,ubuntu,os,open-source,free',
            },
            {
                'product_name': 'Ubuntu 22.04 LTS',
                'version': '22.04 LTS',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Canonical',
                'publisher': 'Canonical',
                'platforms': 'linux',
                'description': 'Ubuntu 22.04 LTS (Jammy Jellyfish) is a stable and reliable Linux distribution backed by Canonical. Features GNOME desktop, Snap package manager, and enterprise-grade security.',
                'short_description': 'Stable and reliable LTS release for production environments.',
                'max_devices': 999,
                'tags': 'linux,ubuntu,os,open-source,free',
            },
            {
                'product_name': 'Debian 12',
                'version': '12 (Bookworm)',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Debian Project',
                'publisher': 'Debian Project',
                'platforms': 'linux',
                'description': 'Debian 12 Bookworm is a free and open-source Linux distribution known for its stability and package management. The universal operating system suitable for desktops, servers, and embedded systems.',
                'short_description': 'The universal open-source OS known for rock-solid stability.',
                'max_devices': 999,
                'tags': 'linux,debian,os,open-source,free,stable',
            },
            {
                'product_name': 'Fedora Workstation 40',
                'version': '40',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Red Hat',
                'publisher': 'Fedora Project',
                'platforms': 'linux',
                'description': 'Fedora Workstation 40 is a cutting-edge Linux distribution featuring the latest GNOME desktop, modern development tools, and strong security features. Backed by Red Hat.',
                'short_description': 'Cutting-edge Linux OS with the latest features and tools.',
                'max_devices': 999,
                'tags': 'linux,fedora,os,open-source,free',
            },
            {
                'product_name': 'Arch Linux',
                'version': 'Rolling Release',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Arch Linux Team',
                'publisher': 'Arch Linux',
                'platforms': 'linux',
                'description': 'Arch Linux is a lightweight and flexible Linux distribution that follows a rolling-release model. Known for its simplicity, customizability, and the powerful Arch User Repository (AUR).',
                'short_description': 'Lightweight rolling-release Linux for power users.',
                'max_devices': 999,
                'tags': 'linux,arch,os,open-source,free,rolling',
            },
            {
                'product_name': 'Kali Linux',
                'version': '2024.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Offensive Security',
                'publisher': 'Offensive Security',
                'platforms': 'linux',
                'description': 'Kali Linux is the industry-standard penetration testing and security auditing distribution. Pre-loaded with hundreds of security tools for network analysis, vulnerability assessment, and digital forensics.',
                'short_description': 'Industry-standard penetration testing and security OS.',
                'max_devices': 999,
                'tags': 'linux,kali,security,os,open-source,free,penetration-testing',
            },
            {
                'product_name': 'Linux Mint 21',
                'version': '21.3 (Virginia)',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Linux Mint Team',
                'publisher': 'Linux Mint Project',
                'platforms': 'linux',
                'description': 'Linux Mint 21 is a beginner-friendly Linux distribution based on Ubuntu. Features the Cinnamon desktop environment with a classic and intuitive interface for users transitioning from Windows.',
                'short_description': 'Beginner-friendly Linux with a classic Windows-like interface.',
                'max_devices': 999,
                'tags': 'linux,mint,os,open-source,free,beginner',
            },
        ],
    },
    'office-suite': {
        'type': 'Office Suite',
        'products': [
            {
                'product_name': 'Microsoft Office 2024 Professional Plus',
                'version': '2024',
                'price': '439.00',
                'compare_price': '499.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows',
                'description': 'The complete office suite with Word, Excel, PowerPoint, Outlook, Access, Publisher, and OneNote. One-time purchase includes all core productivity tools for professional use.',
                'short_description': 'Full office suite with Word, Excel, PowerPoint, Outlook, Access, and Publisher.',
                'max_devices': 1,
                'tags': 'office,microsoft,productivity,word,excel',
            },
            {
                'product_name': 'Microsoft Office 2024 Home & Business',
                'version': '2024',
                'price': '249.00',
                'compare_price': '299.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos',
                'description': 'Essential office applications for home and small business. Includes Word, Excel, PowerPoint, Outlook, and OneNote with a one-time purchase for one computer.',
                'short_description': 'Essential office suite with Word, Excel, PowerPoint, and Outlook.',
                'max_devices': 1,
                'tags': 'office,microsoft,productivity,home,business',
            },
            {
                'product_name': 'Microsoft Office 2024 Home & Student',
                'version': '2024',
                'price': '149.00',
                'compare_price': '179.00',
                'license_type': 'one_time',
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos',
                'description': 'Perfect for students and families. Includes Word, Excel, PowerPoint, and OneNote for school projects, resumes, and household budgeting.',
                'short_description': 'Essential office apps for students and families.',
                'max_devices': 1,
                'tags': 'office,microsoft,student,productivity',
            },
            {
                'product_name': 'Microsoft 365 Personal',
                'version': '2024',
                'price': '6.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos,web,mobile',
                'description': 'Premium Office apps plus 1TB of OneDrive cloud storage, advanced security, and continuous updates. Works on PC, Mac, tablet, and phone.',
                'short_description': 'Premium Office suite with 1TB cloud storage for one person.',
                'max_devices': 5,
                'tags': 'office,microsoft,365,subscription,cloud',
            },
            {
                'product_name': 'Microsoft 365 Family',
                'version': '2024',
                'price': '9.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Microsoft',
                'publisher': 'Microsoft',
                'platforms': 'windows,macos,web,mobile',
                'description': 'Premium Office apps for up to 6 people with 1TB of OneDrive cloud storage each, advanced security, and continuous updates for the whole family.',
                'short_description': 'Premium Office suite with 1TB cloud storage for up to 6 people.',
                'max_devices': 5,
                'tags': 'office,microsoft,365,subscription,family',
            },
            {
                'product_name': 'LibreOffice',
                'version': '24.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'The Document Foundation',
                'publisher': 'The Document Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'LibreOffice is a powerful, free office suite compatible with Microsoft Office formats. Includes Writer (word processing), Calc (spreadsheets), Impress (presentations), Draw, Base (database), and Math.',
                'short_description': 'Powerful free office suite compatible with Microsoft formats.',
                'max_devices': 999,
                'tags': 'office,free,open-source,libreoffice,writer,calc',
            },
            {
                'product_name': 'Apache OpenOffice',
                'version': '4.1',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Apache Software Foundation',
                'publisher': 'Apache Software Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'Apache OpenOffice is a leading open-source office suite with word processing, spreadsheets, presentations, graphics, databases, and more. Fully compatible with Microsoft Office formats.',
                'short_description': 'Feature-rich open-source office suite for everyday productivity.',
                'max_devices': 999,
                'tags': 'office,free,open-source,apache,writer,calc',
            },
            {
                'product_name': 'OnlyOffice Docs',
                'version': '8.0',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Ascensio System SIA',
                'publisher': 'OnlyOffice',
                'platforms': 'windows,macos,linux,web',
                'description': 'OnlyOffice Docs is a free and open-source office suite that provides high compatibility with Microsoft Office formats. Features collaborative document editing, spreadsheets, and presentations.',
                'short_description': 'Collaborative office suite with excellent Microsoft format compatibility.',
                'max_devices': 999,
                'tags': 'office,free,open-source,collaborative,cloud',
            },
        ],
    },
    'design-creative': {
        'type': 'Design & Creative',
        'products': [
            {
                'product_name': 'Adobe Photoshop',
                'version': '2025',
                'price': '22.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'The industry standard for digital image editing and graphic design. Features AI-powered tools including Generative Fill, Neural Filters, advanced layer management, and professional-grade retouching capabilities.',
                'short_description': 'Industry-leading image editing and graphic design software.',
                'max_devices': 2,
                'tags': 'adobe,photoshop,design,photo-editing,graphic-design',
            },
            {
                'product_name': 'Adobe Illustrator',
                'version': '2025',
                'price': '22.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'The industry-standard vector graphics design software for creating logos, icons, illustrations, typography, and complex graphics for print, web, and video.',
                'short_description': 'Professional vector graphics design for logos and illustrations.',
                'max_devices': 2,
                'tags': 'adobe,illustrator,vector,design,graphics',
            },
            {
                'product_name': 'Adobe InDesign',
                'version': '2025',
                'price': '22.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'The premier page layout and design software for print and digital media. Ideal for creating magazines, brochures, eBooks, posters, and interactive PDFs.',
                'short_description': 'Professional page layout and publishing software.',
                'max_devices': 2,
                'tags': 'adobe,indesign,layout,publishing,print',
            },
            {
                'product_name': 'Adobe Creative Cloud All Apps',
                'version': '2025',
                'price': '54.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'Get access to 20+ creative desktop and mobile apps including Photoshop, Illustrator, InDesign, Premiere Pro, After Effects, and more. The complete creative toolkit.',
                'short_description': 'Complete collection of 20+ Adobe creative desktop and mobile apps.',
                'max_devices': 2,
                'tags': 'adobe,creative-cloud,design,complete-suite',
            },
            {
                'product_name': 'GIMP',
                'version': '2.10',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'The GIMP Team',
                'publisher': 'GNU Project',
                'platforms': 'windows,macos,linux',
                'description': 'GNU Image Manipulation Program is a powerful free and open-source image editor. Features advanced photo retouching, image composition, and image authoring tools comparable to professional software.',
                'short_description': 'Free and powerful open-source image editor.',
                'max_devices': 999,
                'tags': 'gimp,image-editor,free,open-source,photo',
            },
            {
                'product_name': 'Inkscape',
                'version': '1.3',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Inkscape Project',
                'publisher': 'Inkscape Project',
                'platforms': 'windows,macos,linux',
                'description': 'Inkscape is a professional vector graphics editor for creating illustrations, diagrams, logos, and complex artwork. Uses SVG as its native format with broad format compatibility.',
                'short_description': 'Professional free vector graphics editor for illustrations and logos.',
                'max_devices': 999,
                'tags': 'inkscape,vector,graphics,free,open-source,svg',
            },
            {
                'product_name': 'Blender',
                'version': '4.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Blender Foundation',
                'publisher': 'Blender Foundation',
                'platforms': 'windows,macos,linux',
                'description': 'Blender is the free and open-source 3D creation suite supporting the entire 3D pipeline: modeling, rigging, animation, simulation, rendering, compositing, motion tracking, video editing, and game creation.',
                'short_description': 'Complete free 3D creation suite for modeling, animation, and rendering.',
                'max_devices': 999,
                'tags': 'blender,3d,modeling,animation,free,open-source',
            },
            {
                'product_name': 'Figma',
                'version': '2024',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Figma',
                'publisher': 'Figma Inc',
                'platforms': 'web,macos,windows',
                'description': 'Figma is a collaborative web-based UI/UX design tool. Teams can design, prototype, and gather feedback in real-time. Free starter plan with paid professional and organization tiers.',
                'short_description': 'Collaborative web-based UI/UX design and prototyping tool.',
                'max_devices': 999,
                'tags': 'figma,ui,ux,design,prototyping,collaboration',
            },
        ],
    },
    'video-editing': {
        'type': 'Video Editing',
        'products': [
            {
                'product_name': 'Adobe Premiere Pro',
                'version': '2025',
                'price': '22.99',
                'license_type': 'subscription_monthly',
                'subscription_duration': 1,
                'developer': 'Adobe',
                'publisher': 'Adobe',
                'platforms': 'windows,macos',
                'description': 'The industry-leading video editing software for film, TV, and the web. Features AI-powered tools like Auto Reframe, Speech to Text, and advanced color grading.',
                'short_description': 'Professional video editing software for film, TV, and web.',
                'max_devices': 2,
                'tags': 'adobe,premiere,pro,video-editing,professional',
            },
            {
                'product_name': 'DaVinci Resolve',
                'version': '19',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Blackmagic Design',
                'publisher': 'Blackmagic Design',
                'platforms': 'windows,macos,linux',
                'description': 'DaVinci Resolve combines professional editing, color correction, visual effects, motion graphics, and audio post-production in one free application. The Studio version adds advanced features.',
                'short_description': 'Professional-grade video editing, color grading, and effects (free version).',
                'max_devices': 999,
                'tags': 'davinci,resolve,video-editing,color-grading,free',
            },
            {
                'product_name': 'DaVinci Resolve Studio',
                'version': '19',
                'price': '295.00',
                'compare_price': '399.00',
                'license_type': 'one_time',
                'developer': 'Blackmagic Design',
                'publisher': 'Blackmagic Design',
                'platforms': 'windows,macos,linux',
                'description': 'The paid version of DaVinci Resolve with advanced features including noise reduction, HDR grading, facial recognition, and collaborative workflow tools. One-time purchase includes lifetime updates.',
                'short_description': 'Professional color grading and video editing with advanced features.',
                'max_devices': 1,
                'tags': 'davinci,resolve,video-editing,professional,studio',
            },
            {
                'product_name': 'Shotcut',
                'version': '24.06',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Meltytech',
                'publisher': 'Meltytech',
                'platforms': 'windows,macos,linux',
                'description': 'Shotcut is a free, open-source, cross-platform video editor with support for a wide range of formats. Features include timeline editing, filters, transitions, and 4K resolution support.',
                'short_description': 'Free open-source video editor with broad format support.',
                'max_devices': 999,
                'tags': 'shotcut,video-editing,free,open-source,cross-platform',
            },
            {
                'product_name': 'OBS Studio',
                'version': '30.2',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'OBS Project',
                'publisher': 'OBS Project',
                'platforms': 'windows,macos,linux',
                'description': 'Open Broadcaster Software is a free and open-source software for video recording and live streaming. Used by millions for professional-quality streaming to Twitch, YouTube, Facebook, and more.',
                'short_description': 'Free open-source software for live streaming and recording.',
                'max_devices': 999,
                'tags': 'obs,streaming,recording,free,open-source,live',
            },
        ],
    },
    'antivirus-security': {
        'type': 'Antivirus & Security',
        'products': [
            {
                'product_name': 'Norton 360 Deluxe',
                'version': '2024',
                'price': '49.99',
                'compare_price': '79.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'NortonLifeLock',
                'publisher': 'Gen Digital',
                'platforms': 'windows,macos,android,ios',
                'description': 'Comprehensive security suite including antivirus, VPN, password manager, dark web monitoring, and 50GB cloud backup. Protects up to 5 devices.',
                'short_description': 'All-in-one security with VPN, password manager, and dark web monitoring.',
                'max_devices': 5,
                'tags': 'norton,antivirus,security,vpn,protection',
            },
            {
                'product_name': 'Bitdefender Total Security',
                'version': '2024',
                'price': '49.99',
                'compare_price': '74.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'Bitdefender',
                'publisher': 'Bitdefender',
                'platforms': 'windows,macos,android,ios',
                'description': 'Multi-layer protection against malware, ransomware, and phishing. Includes VPN, parental controls, webcam protection, and system optimization tools.',
                'short_description': 'Multi-layer protection with VPN, parental controls, and optimization.',
                'max_devices': 5,
                'tags': 'bitdefender,antivirus,security,vpn,parental-control',
            },
            {
                'product_name': 'Kaspersky Internet Security',
                'version': '2024',
                'price': '49.99',
                'compare_price': '69.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'Kaspersky',
                'publisher': 'Kaspersky Lab',
                'platforms': 'windows,macos,android,ios',
                'description': 'Advanced security against viruses, ransomware, and online threats. Features include safe banking, privacy protection, parental controls, and VPN.',
                'short_description': 'Advanced internet security with safe banking and privacy tools.',
                'max_devices': 5,
                'tags': 'kaspersky,antivirus,security,vpn,banking',
            },
            {
                'product_name': 'Malwarebytes Premium',
                'version': '2024',
                'price': '44.99',
                'compare_price': '59.99',
                'license_type': 'subscription_yearly',
                'subscription_duration': 12,
                'developer': 'Malwarebytes',
                'publisher': 'Malwarebytes',
                'platforms': 'windows,macos,android,ios',
                'description': 'Real-time protection against malware, ransomware, and malicious websites. Lightweight and fast, Malwarebytes complements traditional antivirus with advanced threat detection.',
                'short_description': 'Real-time anti-malware protection for advanced threat defense.',
                'max_devices': 5,
                'tags': 'malwarebytes,antivirus,security,anti-malware',
            },
            {
                'product_name': 'Avast Free Antivirus',
                'version': '2024',
                'price': '0.01',
                'license_type': 'freemium',
                'developer': 'Avast',
                'publisher': 'Gen Digital',
                'platforms': 'windows,macos,android,ios',
                'description': 'Free antivirus protection with intelligent threat detection, Wi-Fi security scanner, and password protection. Premium features available for upgrade.',
                'short_description': 'Free antivirus with smart threat detection and Wi-Fi security.',
                'max_devices': 1,
                'tags': 'avast,antivirus,security,free,protection',
            },
            {
                'product_name': 'ClamAV',
                'version': '1.3',
                'price': '0.01',
                'license_type': 'open_source',
                'developer': 'Cisco',
                'publisher': 'Cisco',
                'platforms': 'linux,windows,macos',
                'description': 'ClamAV is an open-source antivirus toolkit designed for detecting trojans, viruses, malware, and other malicious threats. Widely used on mail gateways and Linux servers.',
                'short_description': 'Open-source antivirus toolkit for threat detection.',
                'max_devices': 999,
                'tags': 'clamav,antivirus,security,open-source,free',
            },
        ],
    },
}


class Command(BaseCommand):
    help = 'Seeds the database with popular software products for the software section.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear existing software products before seeding.',
        )

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write(self.style.WARNING('Clearing existing software products...'))
            SoftwareProduct.objects.all().delete()

        try:
            software_category = Category.objects.get(slug='software')
        except Category.DoesNotExist:
            self.stdout.write(self.style.ERROR('Software category not found. Run seed_catalogue first.'))
            return

        for slug, group in SOFTWARE_DATA.items():
            try:
                software_type = SoftwareTypes.objects.get(slug=slug)
            except SoftwareTypes.DoesNotExist:
                self.stdout.write(self.style.WARNING(f'  Software type "{slug}" not found — skipping.'))
                continue

            section_created = 0
            for data in group['products']:
                base_slug = slugify(data['product_name'])
                _, created = SoftwareProduct.objects.get_or_create(
                    slug=base_slug,
                    defaults={
                        'product_name': data['product_name'],
                        'category': software_category,
                        'software_category': software_type,
                        'version': data['version'],
                        'price': data['price'],
                        'stock': 9999,
                        'is_available': True,
                        'is_digital': True,
                        'requires_shipping': False,
                        'track_inventory': False,
                        'description': data.get('description', ''),
                        'short_description': data.get('short_description', ''),
                        'tags': data.get('tags', ''),
                        'license_type': data['license_type'],
                        'platforms': data.get('platforms', 'web'),
                        'developer': data.get('developer', ''),
                        'publisher': data.get('publisher', ''),
                        'max_devices': data.get('max_devices', 1),
                        'subscription_duration': data.get('subscription_duration', None),
                        'compare_price': data.get('compare_price', None),
                        'condition': 'new',
                    }
                )
                if created:
                    section_created += 1

            self.stdout.write(
                f'  {group["type"]}: {section_created} created'
                if section_created
                else self.style.WARNING(f'  {group["type"]}: already exists')
            )

        total = SoftwareProduct.objects.count()
        self.stdout.write(self.style.SUCCESS(f'\n {total} software products seeded successfully!\n'))
