# Generated by Django 6.0.8 on 2026-08-07 05:39

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("supplier_url", models.URLField()),
                ("sku", models.CharField(blank=True, max_length=100)),
                (
                    "supplier_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Set manually for now; Step 3.1's PricingEngine will compute this from a rule.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("CNY", "Chinese Yuan"),
                            ("GHS", "Ghanaian Cedi"),
                            ("NGN", "Nigerian Naira"),
                            ("OTHER", "Other"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("out_of_stock", "Out of stock"),
                            ("scrape_failed", "Scrape failed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, help_text="List of image URLs."),
                ),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "check_frequency_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="How often the Price Monitor Engine (Step 2.2) should check this product.",
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "status"], name="products_pr_owner_i_f7f09c_idx"),
                    models.Index(fields=["supplier"], name="products_pr_supplie_03c6c6_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True), models.Q(("sku", ""), _negated=True)
                        ),
                        fields=("owner", "sku"),
                        name="unique_active_sku_per_owner",
                    )
                ],
            },
        ),
    ]
