# Generated by Django 6.0.8 on 2026-08-08 06:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pricing_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, PriceMonitorService recomputes selling_price from this rule whenever supplier_price changes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="pricing.pricingrule",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Auto-computed from pricing_rule when set; otherwise set manually.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
