# Generated by Django 6.0.8 on 2026-08-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_pricing_rule_alter_product_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier_url",
            field=models.URLField(max_length=500),
        ),
    ]
