# Generated by Django 6.0.8 on 2026-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_supplier_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier_url",
            field=models.URLField(max_length=2000),
        ),
    ]
