# Generated by Django 5.1.4 on 2025-03-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_variations'),
        ('orders', '0005_remove_orderproduct_variations'),
        ('store', '0002_alter_variation_variation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('brand', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=100)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_size', models.CharField(max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='PeripheralProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('brand', models.CharField(max_length=100)),
                ('connectivity', models.CharField(blank=True, max_length=100, null=True)),
                ('compatibility', models.CharField(max_length=200)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('software_type', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('license_type', models.CharField(choices=[('One-time', 'One-time'), ('Subscription', 'Subscription')], max_length=50)),
                ('platform', models.CharField(max_length=100)),
                ('download_link', models.URLField(blank=True, null=True)),
            ],
            bases=('store.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
