# Generated by Django 5.1.4 on 2025-03-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_computertypes'),
        ('store', '0003_computerproduct_peripheralproduct_softwareproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerproduct',
            name='computer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.computertypes'),
        ),
    ]
