# Generated by Django 5.1.4 on 2025-04-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_softwaretypes'),
        ('store', '0004_computerproduct_computer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='software_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.softwaretypes'),
        ),
    ]
