# Generated by Django 5.1.4 on 2025-04-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_softwaretypes_options'),
        ('store', '0005_alter_softwareproduct_software_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='software_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.softwaretypes'),
        ),
    ]
