# Generated by Django 5.1.4 on 2025-04-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_softwareproduct_software_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='software_type',
            field=models.CharField(max_length=100),
        ),
    ]
