# Generated by Django 5.1.4 on 2025-06-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_softwareproduct_software_type'),
    ]

    operations = [
    ]
