# Generated by Django 5.1.4 on 2025-06-25 15:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_category_options_alter_computertypes_options_and_more'),
        ('store', '0008_auto_20250625_1536'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos/brands')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('group', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('attributes', models.JSONField(default=dict, help_text="e.g., {'color': 'red', 'size': 'large'}")),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/variants')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='computerproduct',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='computerproduct',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='computerproduct',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='computerproduct',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='peripheralproduct',
            name='warranty',
        ),
        migrations.RemoveField(
            model_name='softwareproduct',
            name='platform',
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='additional_storage_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='backlit_keyboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='battery_life',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='bluetooth_version',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='fingerprint_reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='gpu_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='gpu_memory',
            field=models.PositiveIntegerField(blank=True, help_text='GPU memory in GB', null=True),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='max_ram',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum RAM in GB', null=True),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='processor_brand',
            field=models.CharField(blank=True, choices=[('intel', 'Intel'), ('amd', 'AMD'), ('apple', 'Apple Silicon'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='processor_cores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='processor_generation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='processor_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='processor_speed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='ram_expandable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='ram_size',
            field=models.PositiveIntegerField(blank=True, help_text='RAM in GB', null=True),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='ram_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='refresh_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Hz', null=True),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='screen_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='storage_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Storage in GB', null=True),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('hdd', 'HDD'), ('ssd', 'SSD'), ('hybrid', 'Hybrid'), ('emmc', 'eMMC')], max_length=20),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='touchscreen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='webcam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerproduct',
            name='wifi_standard',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='battery_life',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='battery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='battery_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='power_consumption',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='peripheralproduct',
            name='warranty_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_backorders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price for discount display', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal cost for profit calculations', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='temp-sku', help_text='Stock Keeping Unit', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image_type',
            field=models.CharField(choices=[('main', 'Main Product Image'), ('gallery', 'Gallery Image'), ('thumbnail', 'Thumbnail'), ('zoom', 'Zoom Image'), ('lifestyle', 'Lifestyle Image')], default='gallery', max_length=20),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='developer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='installation_guide',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='license_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='max_devices',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='platforms',
            field=models.CharField(default='web', help_text='Comma-separated platform list', max_length=200),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='subscription_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in months', null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='system_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computerproduct',
            name='operating_system',
            field=models.CharField(blank=True, default='Windows 10', max_length=100),
        ),
        migrations.AlterField(
            model_name='computerproduct',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peripheralproduct',
            name='compatibility',
            field=models.TextField(help_text='Compatible devices/systems'),
        ),
        migrations.AlterField(
            model_name='peripheralproduct',
            name='connectivity',
            field=models.CharField(blank=True, choices=[('wired_usb', 'Wired USB'), ('wired_usbc', 'Wired USB-C'), ('wireless_2.4ghz', 'Wireless 2.4GHz'), ('bluetooth', 'Bluetooth'), ('wifi', 'Wi-Fi'), ('thunderbolt', 'Thunderbolt'), ('hdmi', 'HDMI'), ('displayport', 'DisplayPort')], default='wired_usb', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.product'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='license_type',
            field=models.CharField(choices=[('one_time', 'One-time Purchase'), ('subscription_monthly', 'Monthly Subscription'), ('subscription_yearly', 'Yearly Subscription'), ('freemium', 'Freemium'), ('open_source', 'Open Source')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='store_produ_sku_8a55cb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'stock'], name='store_produ_is_avai_30b56b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='store_produ_categor_2f0f44_idx'),
        ),
        migrations.AlterField(
            model_name='computerproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
        ),
        migrations.AlterField(
            model_name='peripheralproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='store.product'),
        ),
        migrations.AddField(
            model_name='producttagrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='producttagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producttag'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.reviewrating'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='producttagrelation',
            unique_together={('product', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
    ]
