# Generated by Django 5.1.4 on 2026-04-07 15:25

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_computertypes_parent'),
        ('store', '0009_brand_productspecification_producttag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerproduct',
            name='computer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.computertypes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=store.models.generate_sku, editable=False, help_text='Stock Keeping Unit', max_length=50, unique=True),
        ),
    ]
