# Generated by Django 5.1.4 on 2026-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_description_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Fresh in Box'), ('slightly_used', 'Slightly Used')], default='new', max_length=20),
        ),
    ]
