# Generated by Django 5.1.4 on 2026-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField(choices=[(1, 'Slide 1 (AI Performance)'), (2, 'Slide 2 (IT Services)'), (3, 'Slide 3 (Upgrades)'), (4, 'Slide 4 (Enterprise Solutions)')], help_text='Which slide this banner represents (1 to 4)', unique=True)),
                ('title_main', models.CharField(help_text='Main heading text', max_length=200)),
                ('title_highlight', models.CharField(blank=True, help_text='Highlighted part of heading', max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('button_text', models.CharField(default='Explore Solutions', max_length=50)),
                ('button_link', models.CharField(default='/store/', help_text='Can be relative like /store/ or absolute like https://...', max_length=200)),
                ('background_image', models.ImageField(upload_to='photos/banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this custom banner and show the default one.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
                'ordering': ['slide_number'],
            },
        ),
    ]
