# Generated by Django 5.1.4 on 2026-04-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkingProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('switch_unmanaged', 'Unmanaged Switch'), ('switch_managed', 'Managed Switch'), ('switch_poe', 'PoE Switch'), ('router', 'Router'), ('modem', 'Modem'), ('modem_router', 'Modem/Router Combo'), ('access_point', 'Access Point')], max_length=30)),
                ('total_ports', models.PositiveIntegerField(blank=True, help_text='Total number of ports', null=True)),
                ('uplink_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('poe_support', models.BooleanField(default=False, verbose_name='PoE Support')),
                ('poe_budget_watts', models.PositiveIntegerField(blank=True, help_text='Total PoE budget in Watts', null=True)),
                ('switching_capacity', models.CharField(blank=True, help_text='e.g. 16 Gbps', max_length=50)),
                ('max_speed', models.CharField(blank=True, help_text='e.g. 1 Gbps, 10 Gbps', max_length=50)),
                ('wifi_standard', models.CharField(choices=[('none', 'No Wi-Fi / Wired Only'), ('wifi4', 'Wi-Fi 4 (802.11n)'), ('wifi5', 'Wi-Fi 5 (802.11ac)'), ('wifi6', 'Wi-Fi 6 (802.11ax)'), ('wifi6e', 'Wi-Fi 6E')], default='none', max_length=20)),
                ('wifi_speed', models.CharField(blank=True, help_text='e.g. AX3000, AC1200', max_length=50)),
                ('dual_band', models.BooleanField(default=False)),
                ('wan_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('dsl_type', models.CharField(blank=True, help_text='e.g. ADSL2+, VDSL2, Fibre', max_length=50)),
                ('managed', models.BooleanField(default=False)),
                ('vlan_support', models.BooleanField(default=False)),
                ('rack_mountable', models.BooleanField(default=False)),
                ('warranty_period', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
            options={
                'verbose_name': 'Networking Product',
                'verbose_name_plural': 'Networking Products',
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='SecurityCameraProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('camera_type', models.CharField(choices=[('ip_camera', 'IP / Network Camera'), ('ptz_camera', 'PTZ Camera'), ('dome_camera', 'Dome Camera'), ('bullet_camera', 'Bullet Camera'), ('fisheye_camera', 'Fisheye Camera'), ('doorbell_camera', 'Video Doorbell'), ('nvr', 'NVR (Network Video Recorder)'), ('dvr', 'DVR (Digital Video Recorder)'), ('cctv_kit', 'Complete CCTV Kit')], max_length=30)),
                ('resolution', models.CharField(blank=True, choices=[('720p', '720p HD'), ('1080p', '1080p Full HD'), ('2mp', '2MP'), ('4mp', '4MP'), ('5mp', '5MP'), ('4k', '4K Ultra HD'), ('8mp', '8MP')], max_length=20)),
                ('night_vision', models.BooleanField(default=False)),
                ('night_vision_range', models.PositiveIntegerField(blank=True, help_text='Night vision range in metres', null=True)),
                ('wide_angle', models.CharField(blank=True, help_text='e.g. 120°, 180°', max_length=20)),
                ('connectivity', models.CharField(blank=True, help_text='e.g. Wired PoE, Wi-Fi, 4G', max_length=50)),
                ('poe_powered', models.BooleanField(default=False, verbose_name='PoE Powered')),
                ('storage_type', models.CharField(blank=True, choices=[('sd_card', 'SD Card'), ('cloud', 'Cloud Storage'), ('hdd_nvr', 'HDD via NVR/DVR'), ('local_nas', 'NAS')], max_length=20)),
                ('max_sd_card_gb', models.PositiveIntegerField(blank=True, help_text='Max SD card size in GB', null=True)),
                ('number_of_cameras', models.PositiveIntegerField(blank=True, help_text='Cameras included in kit', null=True)),
                ('hdd_included_tb', models.DecimalField(blank=True, decimal_places=1, help_text='HDD included (TB)', max_digits=4, null=True)),
                ('channels', models.PositiveIntegerField(blank=True, help_text='Number of channels (NVR/DVR)', null=True)),
                ('motion_detection', models.BooleanField(default=False)),
                ('two_way_audio', models.BooleanField(default=False)),
                ('weatherproof', models.BooleanField(default=False)),
                ('weatherproof_rating', models.CharField(blank=True, help_text='e.g. IP67', max_length=20)),
                ('ai_detection', models.BooleanField(default=False, verbose_name='AI/Smart Detection')),
                ('warranty_period', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
            options={
                'verbose_name': 'Security Camera / System',
                'verbose_name_plural': 'Security Cameras & Systems',
            },
            bases=('store.product',),
        ),
    ]
