# Generated by Django 5.1.4 on 2026-04-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_computertypes_parent'),
        ('store', '0014_networkingproduct_securitycameraproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computerproduct',
            options={'verbose_name': '💻 Computer Product', 'verbose_name_plural': '💻 Computer Products'},
        ),
        migrations.AlterModelOptions(
            name='networkingproduct',
            options={'verbose_name': '🌐 Networking Product', 'verbose_name_plural': '🌐 Networking Products'},
        ),
        migrations.AlterModelOptions(
            name='peripheralproduct',
            options={'verbose_name': '🔌 Peripheral Product', 'verbose_name_plural': '🔌 Peripheral Products'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date'], 'verbose_name': 'Base Product (do not use directly)', 'verbose_name_plural': 'Base Products (do not use directly)'},
        ),
        migrations.AlterModelOptions(
            name='securitycameraproduct',
            options={'verbose_name': '📷 Security Camera / CCTV', 'verbose_name_plural': '📷 Security Cameras & CCTV'},
        ),
        migrations.AlterModelOptions(
            name='softwareproduct',
            options={'verbose_name': '💾 Software Product', 'verbose_name_plural': '💾 Software Products'},
        ),
        migrations.RemoveField(
            model_name='softwareproduct',
            name='software_type',
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='software_category',
            field=models.ForeignKey(blank=True, help_text='Select the category this software belongs to (e.g. Antivirus, Office Suite).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.softwaretypes', verbose_name='Software Type'),
        ),
    ]
