# Generated by Django 5.1.4 on 2026-04-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_software_product_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='for_computers',
            field=models.BooleanField(default=False, verbose_name='Computers / Laptops / Desktops'),
        ),
        migrations.AddField(
            model_name='brand',
            name='for_networking',
            field=models.BooleanField(default=False, verbose_name='Networking (Switches, Routers, APs)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='for_peripherals',
            field=models.BooleanField(default=False, verbose_name='Peripherals & Accessories'),
        ),
        migrations.AddField(
            model_name='brand',
            name='for_security',
            field=models.BooleanField(default=False, verbose_name='Security / CCTV Cameras'),
        ),
        migrations.AddField(
            model_name='brand',
            name='for_software',
            field=models.BooleanField(default=False, verbose_name='Software'),
        ),
    ]
