# Generated by Django 5.1.4 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_brand_product_group_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkingproduct',
            name='device_type',
            field=models.CharField(
                choices=[
                    ('switch_unmanaged', 'Unmanaged Switch'),
                    ('switch_managed', 'Managed Switch'),
                    ('switch_poe', 'PoE Switch'),
                    ('router', 'Router'),
                    ('modem', 'Modem'),
                    ('modem_router', 'Modem/Router Combo'),
                    ('access_point', 'Access Point'),
                    ('ups', 'UPS (Uninterruptible Power Supply)'),
                ],
                max_length=30,
            ),
        ),
    ]
