# Generated by Django 5.1.4 on 2026-05-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_networkingproduct_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='for_ups',
            field=models.BooleanField(default=False, verbose_name='UPS (Uninterruptible Power Supplies)'),
        ),
        migrations.AlterField(
            model_name='networkingproduct',
            name='device_type',
            field=models.CharField(choices=[('switch_unmanaged', 'Unmanaged Switch'), ('switch_managed', 'Managed Switch'), ('switch_poe', 'PoE Switch'), ('router', 'Router'), ('modem', 'Modem'), ('modem_router', 'Modem/Router Combo'), ('access_point', 'Access Point')], max_length=30),
        ),
        migrations.CreateModel(
            name='UPSProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('capacity_va', models.PositiveIntegerField(help_text='Capacity in VA (Volt-Amperes)')),
                ('capacity_watts', models.PositiveIntegerField(blank=True, help_text='Capacity in Watts', null=True)),
                ('ups_type', models.CharField(choices=[('standby', 'Standby (Offline)'), ('line_interactive', 'Line Interactive'), ('online_double', 'Online Double Conversion')], default='line_interactive', max_length=30)),
                ('output_type', models.CharField(choices=[('simulated_sine', 'Simulated Sine Wave'), ('pure_sine', 'Pure Sine Wave')], default='simulated_sine', max_length=20)),
                ('form_factor', models.CharField(choices=[('tower', 'Tower'), ('rack', 'Rack Mount'), ('rack_tower', 'Rack / Tower Convertible')], default='tower', max_length=20)),
                ('battery_type', models.CharField(blank=True, help_text='e.g. Sealed Lead Acid, Lithium-ion', max_length=50)),
                ('number_of_batteries', models.PositiveIntegerField(blank=True, null=True)),
                ('replaceable_battery', models.BooleanField(default=True)),
                ('runtime_half_load', models.CharField(blank=True, help_text='Runtime at 50% load, e.g. 15 min', max_length=50)),
                ('runtime_full_load', models.CharField(blank=True, help_text='Runtime at 100% load, e.g. 5 min', max_length=50)),
                ('num_outlets', models.PositiveIntegerField(blank=True, help_text='Total number of outlets', null=True)),
                ('num_battery_backup_outlets', models.PositiveIntegerField(blank=True, help_text='Outlets with battery backup', null=True)),
                ('num_surge_only_outlets', models.PositiveIntegerField(blank=True, help_text='Surge-only outlets', null=True)),
                ('usb_port', models.BooleanField(default=False, verbose_name='USB Monitoring Port')),
                ('network_manageable', models.BooleanField(default=False, help_text='SNMP / network management card')),
                ('surge_protection_joules', models.PositiveIntegerField(blank=True, help_text='Surge protection rating in Joules', null=True)),
                ('avr', models.BooleanField(default=False, verbose_name='Automatic Voltage Regulation (AVR)')),
                ('lcd_display', models.BooleanField(default=False)),
                ('audible_alarm', models.BooleanField(default=True)),
                ('warranty_period', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
            options={
                'verbose_name': '🔋 UPS Product',
                'verbose_name_plural': '🔋 UPS Products',
            },
            bases=('store.product',),
        ),
    ]
