# Generated by Django 4.2.10 on 2026-07-23 13:06

import accounts.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_brand_for_ups_alter_networkingproduct_device_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/brands",
                validators=[accounts.utils.validators.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="homebanner",
            name="background_image",
            field=models.ImageField(
                upload_to="photos/banners/",
                validators=[accounts.utils.validators.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/products",
                validators=[accounts.utils.validators.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(
                max_length=255,
                upload_to="store/products",
                validators=[accounts.utils.validators.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="store/variants",
                validators=[accounts.utils.validators.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="upsproduct",
            name="brand",
            field=models.ForeignKey(
                help_text="Note: Only brands marked as 'For UPS' will appear here.",
                on_delete=django.db.models.deletion.CASCADE,
                to="store.brand",
            ),
        ),
    ]
