"""
Django settings for LiG project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8000,http://127.0.0.1:8000', cast=Csv())


SITE_ID = 2

# Security settings
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 86400  # 24 hours
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Production HTTPS settings (only active when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django.contrib.humanize',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
     #manully added
    'research',
    'froala_editor',
    'checkout',
    'cart',
    'payment',
    'analytics',
    'accounts',
    'category',
    'orders',
    'store',
    'pages',

]

# Froala Editor Settings
FROALA_EDITOR_OPTIONS = {
    'language': 'en',
    'toolbarSticky': False,
    'imageUploadURL': '/froala_editor/image_upload/',
    'fileUploadURL': '/froala_editor/file_upload/',
    'imageAllowedTypes': ['jpeg', 'jpg', 'png', 'gif'],
    'imageInsertButtons': ['imageBack', '|', 'imageUpload', 'imageByURL'],
    'paragraphFormat': {'N': '', 'H1': 'h1', 'H2': 'h2', 'H3': 'h3'},
    'heightMin': 200,
}
FROALA_UPLOAD_PATH = 'uploads/froala_editor/images/'
FILE_UPLOAD_PERMISSIONS = 0o644

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'analytics.middleware.VisitorTrackingMiddleware',
    'accounts.middleware.AdminAutoLogoutMiddleware',
    'accounts.middleware.SecurityHeadersMiddleware',
    'accounts.middleware.AuditMiddleware',
]


# Admin Auto Logout setting (in seconds)
ADMIN_SESSION_EXPIRE_SECONDS = 3600  # 1 hour

ROOT_URLCONF = 'LiG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.counter',
                'pages.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'LiG.wsgi.application'
AUTH_USER_MODEL = 'accounts.Account'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if config('USE_POSTGRES', default=False, cast=bool):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static Files
STATIC_URL = '/static/'  
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

# Media Files
MEDIA_URL = '/media/'  
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = BASE_DIR / 'media'


# Adding another static files directory
STATICFILES_DIRS.append(os.path.join(BASE_DIR, 'LiG/static'))

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}




PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')

# Hubtel Payment Settings
HUBTEL_CLIENT_ID = config('HUBTEL_CLIENT_ID')
HUBTEL_CLIENT_SECRET = config('HUBTEL_CLIENT_SECRET')
HUBTEL_MERCHANT_ACCOUNT_NUMBER = config('HUBTEL_MERCHANT_ACCOUNT_NUMBER', default='')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
   
]

import os

# LOG_DIR = "/var/www/LiG/logs"
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {

    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            "filename": os.path.join(LOG_DIR, "payments.log"),
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'payment': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

load_dotenv()  

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv("GOOGLE_OAUTH_CLIENT_ID"),
            'secret': os.getenv("GOOGLE_OAUTH_CLIENT_SECRET"),
            'key': os.getenv("GOOGLE_OAUTH_KEY", ""),  
        }
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cloudflare Turnstile
TURNSTILE_SITE_KEY = config('TURNSTILE_SITE_KEY', default='')
TURNSTILE_SECRET_KEY = config('TURNSTILE_SECRET_KEY', default='')

# SMTP configuration
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)





JAZZMIN_SETTINGS = {
    "site_title": "LiG Admin",
    "site_header": "LiG Store Administration",
    "site_brand": "LiG Admin",
    "site_icon": "./images/favicon.png",
    "welcome_sign": "Welcome to LiG Administration",
    "copyright": "LiG Store",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "home", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],

    # Sidebar settings
    "show_sidebar": True,
    "navigation_expanded": False,
    "sidebar_fixed": True,

    # Defines grouped, ordered sidebar navigation.
    # Each app string becomes a collapsible section header;
    # the app.Model strings beneath it become nested child links.
    "order_with_respect_to": [
        # -- Analytics -------------------------------------------------------
        "analytics",
        "analytics.DailyStats",
        "analytics.Visitor",
        "analytics.PageView",

        # -- Products --------------------------------------------------------
        "store",
        "store.ComputerProduct",
        "store.SoftwareProduct",
        "store.PeripheralProduct",
        "store.NetworkingProduct",
        "store.UPSProduct",
        "store.SecurityCameraProduct",
        "store.Brand",
        "store.HomeBanner",
        "store.ReviewRating",

        # -- Categories ------------------------------------------------------
        "category",
        "category.Category",
        "category.ComputerTypes",
        "category.SoftwareTypes",
        "category.ResearchTypes",

        # -- Orders ----------------------------------------------------------
        "orders",
        "orders.Order",
        "orders.OrderProduct",
        "orders.PaymentProof",

        # -- Payments --------------------------------------------------------
        "payment",
        "payment.Payment",
        "payment.PaystackPayment",
        "payment.HubtelPayment",

        # -- Accounts & Auth -------------------------------------------------
        "accounts",
        "accounts.Account",
        "accounts.UserProfile",
        "accounts.NewsletterSubscriber",
        "auth",
        "auth.User",
        "auth.Group",
        "accounts.Admin2FA",
        "accounts.AuditLog",

        # -- Content & Pages -------------------------------------------------
        "pages",
        "pages.AboutPage",
        "pages.HelpCategory",
        "pages.HelpArticle",
        "pages.PolicyPage",
        "pages.SiteSettings",

        # -- Research --------------------------------------------------------
        "research",
        "research.ResearchProject",

        # -- System ----------------------------------------------------------
        "admin",
        "admin.LogEntry",
    ],

    "icons": {
        # Auth & Accounts
        "auth": "fas fa-lock",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts": "fas fa-user-circle",
        "accounts.Account": "fas fa-user-shield",
        "accounts.UserProfile": "fas fa-id-card",
        "accounts.Admin2FA": "fas fa-shield-alt",
        "accounts.AuditLog": "fas fa-history",
        "accounts.NewsletterSubscriber": "fas fa-envelope-open-text",
        "admin.LogEntry": "fas fa-clipboard-list",
        # Analytics
        "analytics": "fas fa-chart-line",
        "analytics.Visitor": "fas fa-users",
        "analytics.PageView": "fas fa-eye",
        "analytics.DailyStats": "fas fa-chart-bar",
        # Store Products
        "store": "fas fa-store",
        "store.Product": "fas fa-box",
        "store.ComputerProduct": "fas fa-laptop",
        "store.SoftwareProduct": "fas fa-compact-disc",
        "store.PeripheralProduct": "fas fa-keyboard",
        "store.NetworkingProduct": "fas fa-network-wired",
        "store.UPSProduct": "fas fa-plug",
        "store.SecurityCameraProduct": "fas fa-video",
        "store.Brand": "fas fa-copyright",
        "store.ReviewRating": "fas fa-star",
        "store.HomeBanner": "fas fa-images",
        "store.ProductTag": "fas fa-tags",
        "store.ProductGallery": "fas fa-photo-video",
        "store.ProductSpecification": "fas fa-list-ul",
        "store.ProductVariant": "fas fa-sliders-h",
        # Category
        "category": "fas fa-th-large",
        "category.Category": "fas fa-th-large",
        "category.ComputerTypes": "fas fa-desktop",
        "category.SoftwareTypes": "fas fa-code",
        "category.ResearchTypes": "fas fa-microscope",
        # Orders & Payments
        "orders": "fas fa-shopping-cart",
        "orders.Order": "fas fa-shopping-bag",
        "orders.OrderProduct": "fas fa-boxes",
        "orders.PaymentProof": "fas fa-file-invoice-dollar",
        "payment": "fas fa-credit-card",
        "payment.Payment": "fas fa-credit-card",
        "payment.PaystackPayment": "fas fa-credit-card",
        "payment.HubtelPayment": "fas fa-mobile-alt",
        # Pages & Content
        "pages": "fas fa-file-alt",
        "pages.AboutPage": "fas fa-info-circle",
        "pages.HelpCategory": "fas fa-life-ring",
        "pages.HelpArticle": "fas fa-question-circle",
        "pages.PolicyPage": "fas fa-gavel",
        "pages.SiteSettings": "fas fa-cog",
        # Research
        "research": "fas fa-atom",
        "research.ResearchProject": "fas fa-atom",
        # System
        "admin": "fas fa-tools",
    },

    "custom_links": {
        "analytics": [
            {
                "name": "Analytics Dashboard",
                "url": "dashboard:index",
                "icon": "fas fa-chart-pie",
                "permissions": ["auth.view_user"],
            },
        ],
        "accounts": [
            {
                "name": "Security Settings",
                "url": "admin:2fa_setup",
                "icon": "fas fa-shield-alt",
                "permissions": ["auth.view_user"],
            },
        ],
    },

    "related_modal_active": False,

    "custom_css": """
        /* ── Sidebar shell ──────────────────────────────────────────── */
        .main-sidebar {
            background-color: #1a1d24 !important;
            box-shadow: 2px 0 12px rgba(0, 0, 0, 0.3) !important;
        }
        .main-sidebar .brand-link {
            border-bottom: 1px solid rgba(255, 255, 255, 0.07) !important;
            padding: 14px 16px !important;
            background-color: #15181e !important;
        }
        .main-sidebar .brand-link .brand-text {
            font-weight: 700 !important;
            letter-spacing: 0.4px !important;
            font-size: 1rem !important;
        }
        .sidebar {
            overflow-y: auto !important;
            max-height: calc(100vh - 57px) !important;
            padding: 8px 8px 20px !important;
        }
        .sidebar::-webkit-scrollbar { width: 4px; }
        .sidebar::-webkit-scrollbar-thumb {
            background: rgba(255,255,255,0.12);
            border-radius: 4px;
        }

        /* ── Group header row (app-level toggle) ────────────────────── */
        .nav-sidebar > .nav-item > .nav-link {
            border-radius: 8px !important;
            padding: 13px 14px !important;
            margin-bottom: 4px !important;
            color: #c2c7d0 !important;
            font-size: 0.875rem !important;
            font-weight: 600 !important;
            letter-spacing: 0.2px;
            transition: background 0.18s ease, color 0.18s ease !important;
        }

        /* ── All nav links ──────────────────────────────────────────── */
        .nav-sidebar .nav-item .nav-link {
            border-radius: 8px !important;
            padding: 12px 14px !important;
            margin-bottom: 4px !important;
            color: #c2c7d0 !important;
            font-size: 0.875rem !important;
            font-weight: 500 !important;
            transition: background 0.18s ease, color 0.18s ease !important;
            line-height: 1.4;
        }
        .nav-sidebar .nav-item .nav-link i {
            margin-right: 12px !important;
            font-size: 0.95rem !important;
            opacity: 0.8;
            width: 18px;
            text-align: center;
        }
        .nav-sidebar .nav-item .nav-link:hover {
            background-color: rgba(255,255,255,0.06) !important;
            color: #e8eaed !important;
        }
        .nav-sidebar .nav-item .nav-link.active {
            background-color: rgba(26, 115, 232, 0.18) !important;
            color: #8ab4f8 !important;
            border-left: 3px solid #1a73e8 !important;
            font-weight: 600 !important;
        }

        /* ── Nested child items (model rows inside each group) ──────── */
        .nav-sidebar .nav-treeview {
            padding-left: 4px !important;
            background-color: rgba(0,0,0,0.15) !important;
            border-radius: 0 0 8px 8px !important;
            margin-bottom: 6px;
        }
        .nav-sidebar .nav-treeview .nav-item .nav-link {
            padding: 10px 14px 10px 22px !important;
            font-size: 0.84rem !important;
            color: #9aa0a6 !important;
            font-weight: 400 !important;
            border-radius: 6px !important;
            margin-bottom: 2px !important;
            line-height: 1.4;
        }
        .nav-sidebar .nav-treeview .nav-item .nav-link:hover {
            background-color: rgba(255,255,255,0.05) !important;
            color: #e8eaed !important;
        }
        .nav-sidebar .nav-treeview .nav-item .nav-link.active {
            background-color: rgba(26,115,232,0.15) !important;
            color: #8ab4f8 !important;
            border-left: 3px solid #1a73e8 !important;
        }

        /* ── Caret arrows for collapsible groups ────────────────────── */
        .nav-sidebar .nav-item > .nav-link .right {
            opacity: 0.45;
            font-size: 0.72rem;
            transition: transform 0.2s ease;
        }
        .nav-sidebar .nav-item.menu-open > .nav-link .right {
            transform: rotate(90deg);
            opacity: 0.9;
        }

        /* ── Section labels (nav-header) ────────────────────────────── */
        .nav-sidebar .nav-header {
            font-size: 0.68rem !important;
            font-weight: 700 !important;
            text-transform: uppercase !important;
            letter-spacing: 1px !important;
            color: #5f6368 !important;
            padding: 18px 14px 6px !important;
            margin-top: 6px !important;
        }
    """,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "navbar": "navbar-dark bg-primary",
    "sidebar": "sidebar-dark-primary",
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar_small_text": False,
    "sidebar_nav_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_logo": "images/logo.png",
    "brand_logo_class": "brand-image img-circle elevation-3",
    "brand_logo_alt": "LiG Admin",
}

