# Generated by Django 6.0.8 on 2026-08-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredproduct",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
