# Generated by Django 5.1.4 on 2026-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_options_payment_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('hubtel', 'Hubtel')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='hubtel_checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='hubtel_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
