# Generated by Django 5.1.4 on 2026-04-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_gateway_payment_hubtel_checkout_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubtelPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Hubtel Payment',
                'verbose_name_plural': '📱  Hubtel Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.payment',),
        ),
        migrations.CreateModel(
            name='PaystackPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Paystack Payment',
                'verbose_name_plural': '💳  Paystack Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.payment',),
        ),
    ]
