# Generated by Django 4.2.10 on 2026-07-21 12:07

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="About Us", max_length=200)),
                (
                    "hero_title",
                    models.CharField(
                        default="About LuckyTech Innovation Ground", max_length=200
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Empowering businesses through innovative technology solutions."
                    ),
                ),
                ("mission", models.TextField(blank=True, default="")),
                ("vision", models.TextField(blank=True, default="")),
                ("values", models.TextField(blank=True, default="")),
                ("story", froala_editor.fields.FroalaField(blank=True, default="")),
                (
                    "team_section_title",
                    models.CharField(default="Our Team", max_length=200),
                ),
                (
                    "team_section_content",
                    froala_editor.fields.FroalaField(blank=True, default=""),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="Learn about LuckyTech Innovation Ground - our mission, vision, and team.",
                        max_length=160,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Pages",
            },
        ),
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.CharField(
                        default="fa-question-circle",
                        help_text="Font Awesome icon class (e.g. fa-shopping-cart)",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Help Category",
                "verbose_name_plural": "Help Categories",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", froala_editor.fields.FroalaField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="pages.helpcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Article",
                "verbose_name_plural": "Help Articles",
                "ordering": ["order", "title"],
            },
        ),
    ]
