# Generated by Django 4.2.10 on 2026-07-21 12:29

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("privacy", "Privacy Policy"),
                            ("terms", "Terms of Service"),
                            ("cookies", "Cookie Policy"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", froala_editor.fields.FroalaField()),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policy Page",
                "verbose_name_plural": "Policy Pages",
            },
        ),
    ]
