# Generated by Django 4.2.10 on 2026-07-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_seed_policy_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("internship_portal_enabled", models.BooleanField(default=False)),
                (
                    "internship_portal_url",
                    models.URLField(default="https://internship.lig.com.gh/"),
                ),
                (
                    "internship_portal_label",
                    models.CharField(default="Internship Portal", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
