# Generated by Django 5.0.14 on 2026-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="delivery_fee_koforidua",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Delivery fee charged for deliveries within Koforidua.",
                max_digits=10,
            ),
        ),
    ]
