# Generated by Django 4.2.10 on 2026-06-26 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin2FA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totp_secret", models.CharField(max_length=64)),
                ("is_enabled", models.BooleanField(default=False)),
                ("backup_codes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Successful"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("2FA_SUCCESS", "2FA Successful"),
                            ("2FA_FAILED", "2FA Failed"),
                            ("2FA_ENABLED", "2FA Enabled"),
                            ("2FA_DISABLED", "2FA Disabled"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("ACCOUNT_CREATE", "Account Created"),
                            ("ACCOUNT_UPDATE", "Account Updated"),
                            ("ACCOUNT_DELETE", "Account Deleted"),
                            ("ADMIN_ACTION", "Admin Action"),
                            ("ADMIN_LOGIN_SUCCESS", "Admin Login Successful"),
                            ("ADMIN_LOGIN_FAILED", "Admin Login Failed"),
                            ("ADMIN_2FA_REQUIRED", "Admin 2FA Required"),
                            ("SENSITIVE_ACTION", "Sensitive Action"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("details", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="accounts_au_user_id_96c97d_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="accounts_au_timesta_276167_idx"
                    ),
                ],
            },
        ),
    ]
