# Generated by Django 5.1.4 on 2025-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_computertypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'research type',
                'verbose_name_plural': 'research types',
            },
        ),
    ]
