# Generated by Django 5.1.4 on 2025-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_softwaretypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwaretypes',
            options={'verbose_name': 'Software type', 'verbose_name_plural': 'Software types '},
        ),
        migrations.RenameField(
            model_name='softwaretypes',
            old_name='computer_type',
            new_name='software_type',
        ),
        migrations.AlterField(
            model_name='softwaretypes',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='photos/software_types'),
        ),
    ]
