# Generated by Django 5.1.4 on 2025-04-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_softwaretypes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwaretypes',
            options={'verbose_name': 'Software type', 'verbose_name_plural': 'Software types'},
        ),
    ]
