# Generated by Django 5.1.4 on 2025-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_softwaretypes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'category_name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='computertypes',
            options={'ordering': ['sort_order', 'computer_type'], 'verbose_name': 'computer type', 'verbose_name_plural': 'computer types'},
        ),
        migrations.AlterModelOptions(
            name='researchtypes',
            options={'ordering': ['sort_order', 'research_type'], 'verbose_name': 'research type', 'verbose_name_plural': 'research types'},
        ),
        migrations.AlterModelOptions(
            name='softwaretypes',
            options={'ordering': ['sort_order', 'software_type'], 'verbose_name': 'Software type', 'verbose_name_plural': 'Software types'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computertypes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='computertypes',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchtypes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='researchtypes',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='softwaretypes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='softwaretypes',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
