# Generated by Django 5.1.4 on 2025-07-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_category_options_alter_computertypes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computertypes',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a top-level category like Laptop or Desktop.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.computertypes'),
        ),
    ]
