# Generated by Django 5.2.17 on 2026-08-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_product_store_sync_fields'),
        ('suppliers', '0002_supplier_catalog_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('check_ok', 'Scrape completed (no change)'), ('price_change', 'Price changed'), ('stock_change', 'Stock changed'), ('scrape_failed', 'Scrape failed'), ('removed', 'Product removed from supplier'), ('store_synced', 'Store product synced'), ('store_deleted', 'Store product deleted'), ('discovered', 'New product discovered'), ('imported', 'Discovery imported'), ('status_change', 'Product status changed')], db_index=True, max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='dashboard_a_owner_i_6c5992_idx'), models.Index(fields=['owner', 'event_type', '-created_at'], name='dashboard_a_owner_i_b3bd13_idx')],
            },
        ),
    ]
