# Generated by Django 5.1.4 on 2025-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_blogmodel_category_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('university', models.CharField(max_length=255)),
                ('project_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
