# Generated by Django 5.1.6 on 2025-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('license', 'License Type'), ('subscription', 'Subscription Duration')], max_length=100),
        ),
    ]
