# Generated by Django 6.0.8 on 2026-08-07 11:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("old_stock", models.IntegerField(blank=True, null=True)),
                ("new_stock", models.IntegerField(blank=True, null=True)),
                ("price_changed", models.BooleanField(default=False)),
                ("stock_changed", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="Scraper key, e.g. 'catlog'.", max_length=100
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("scrape", "Automatic scrape"),
                            ("manual", "Manual edit"),
                            ("pricing_rule", "Pricing rule recompute"),
                        ],
                        default="scrape",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "price histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"], name="history_pri_product_5d6d7c_idx"
                    ),
                    models.Index(
                        fields=["owner", "-created_at"], name="history_pri_owner_i_775fa9_idx"
                    ),
                ],
            },
        ),
    ]
