# Generated by Django 5.2.15 on 2026-08-06 10:58

import accounts.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentproof",
            name="proof_image",
            field=models.ImageField(
                upload_to="payment_proofs/",
                validators=[accounts.utils.validators.validate_image],
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _map_old_statuses(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _map_old_statuses(apps):
    Order = apps.get_model("orders", "Order")
    mapping = {
        "New": "Pending",
        "Pending Payment": "Pending",
        "Accepted": "Pending",
        "Completed": "Pending",
        "Expired": "Cancelled",
    }
    for old_status, new_status in mapping.items():
        Order.objects.filter(status=old_status).update(status=new_status)
