# Generated by Django 5.1.4 on 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_status_alter_paymentproof_proof_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentProof",
        ),
    ]
