# Generated by Django 5.0.14 on 2026-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_paymentproof"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("within_koforidua", "Within Koforidua"),
                    ("outside_koforidua", "Outside Koforidua"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_method",
            field=models.CharField(
                choices=[("delivery", "Delivery"), ("pickup", "Pickup at Office")],
                default="delivery",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
