# Generated by Django 6.0.8 on 2026-08-07 05:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField()),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("CNY", "Chinese Yuan"),
                            ("GHS", "Ghanaian Cedi"),
                            ("NGN", "Nigerian Naira"),
                            ("OTHER", "Other"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                ("default_scraper", models.CharField(blank=True, max_length=100)),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Max scrape requests per minute against this supplier's website.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("owner", "name"),
                        name="unique_active_supplier_name_per_owner",
                    )
                ],
            },
        ),
    ]
