# Generated by Django 6.0.8 on 2026-08-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="catalog_url",
            field=models.URLField(
                blank=True,
                help_text="Page listing all products (for discovering new ones). Falls back to `website` if left blank — for a Catlog storefront, the homepage usually *is* the catalog.",
            ),
        ),
    ]
